title: espanso
subtitle: Cross-platform Text Expander written in Rust
description: >- # this means to ignore newlines until "baseurl:"
  An Open Source, Cross-platform Text Expander written in Rust.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://espanso.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  federico-terzi

permalink: /blog/:title/
highlighter: rouge

collections:
  portfolios:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: Federico Terzi
  links:
    - https://www.youtube.com/c/FedericoTerzi
    - https://www.linkedin.com/in/federico-terzi/
    - https://github.com/federico-terzi