[package]
name = "espanso-mac-utils"
version = "0.1.0"
authors = ["Federico Terzi <federico-terzi@users.noreply.github.com>"]
edition = "2021"
build = "build.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.5"

[build-dependencies]
cc = "1.0.73"

[lints]
workspace = true
